spark:
  app_name: fineweb_chinese_dedup_cleaned
pipeline:
  type: ParquetWriter
  shuffle: False
  mode: overwrite
  output_path: /home/dataset/cn_dataset/parquets/Fineweb_Edu_Chinese_dedup_cleaned
  child_configs:
    - type: ChineseCleanAndFilter
      input_col: "text"
      output_col: "text"
      min_length: 50
      child_configs:
        - type: ParquetReader
          input_path: "/home/zh_dataset/Fineweb_Edu_Chinese_dedup/part-*.parquet"
