spark:
  app_name: aligned_zh2en
pipeline:
  type: LanceWriter
  shuffle: False
  mode: overwrite
  select_cols: ["text_tokenized"]
  output_path: /home/dataset/cn_dataset/tokens/undl_zh2en_aligned
  child_configs:
    - type: Tokenization
      input_col: "text"
      output_col: "text_tokenized"
      tokenizer_name_or_path: "/mnt/qwen2_tokenizer/tokenizer"
      child_configs:
        - type: Concat
          select_cols: ["src_text", "dst_text"]
          output_col: "text"
          child_configs:
            - type: LanceReader
              input_path: /home/dataset/cn_dataset/parquets/undl_zh2en_aligned
