ray:
  app_name: alpaca_zh-tokens
pipeline:
  type: LanceWriter
  shuffle: true
  mode: overwrite
  select_cols: ["text_tokenized"]
  output_path: /home/dataset/cn_dataset/tokens/alpaca_zh/
  child_configs:
    - type: Tokenization
      input_col: "text"
      output_col: "text_tokenized"
      tokenizer_name_or_path: "/mnt/qwen2_tokenizer/tokenizer"
      child_configs:
        - type: ConcatenateColumns
          input_cols: ["instruction", "input", "output"]
          output_col: "text"
          separator: "\n"
          child_configs:
            - type: LanceReader
              input_path: /home/dataset/cn_dataset/parquets/alpaca_zh
