ray:
  app_name: baidu_baike-tokens
pipeline:
  type: LanceWriter
  shuffle: False
  mode: overwrite
  select_cols: ["text_tokenized"]
  output_path: /home/dataset/cn_dataset/tokens/baidu_baike
  child_configs:
    - type: Tokenization
      input_col: "_c6"
      output_col: "text_tokenized"
      tokenizer_name_or_path: "/mnt/qwen2_tokenizer/tokenizer"
      child_configs:
        - type: LanceReader
          input_path: /home/dataset/cn_dataset/parquets/baidu_baike
