spark:
  app_name: dclm_tokens_v0
pipeline:
  type: LanceWriter
  output_path: /home/dataset/kaiyuan/v0/dclm_tokens
  select_cols: ["fasttext_openhermes_reddit_eli5_vs_rw_v2_bigram_200k_train_prob", "text_tokenized"]
  shuffle: true
  mode: overwrite
  child_configs:
    - type: Tokenization
      input_col: "text"
      output_col: "text_tokenized"
      tokenizer_name_or_path: "/mnt/qwen2_tokenizer/tokenizer"
      child_configs:
        - type: LanceReader
          input_path: /home/en_dataset/dclm_dedup/part-*.parquet
          num_parallel: 128
