spark:
  app_name: openwebmath_tokens
pipeline:
  type: LanceWriter
  shuffle: False
  mode: overwrite
  select_cols: ["text_tokenized", "meta"]
  output_path: /home/dataset/math_dataset/tokens/open_web_math
  child_configs:
    - type: Tokenization
      input_col: "text"
      output_col: "text_tokenized"
      tokenizer_name_or_path: "/mnt/qwen2_tokenizer/tokenizer"
      child_configs:
        - type: ParseJsonString
          input_col: metadata
          output_col: meta
          child_configs:
            - type: LanceReader
              input_path: /home/dataset/math_dataset/parquets/open-web-math
              mergeSchema: false
