kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kaiyuan-ray
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30900
        hostPort: 30900
        protocol: TCP
      - containerPort: 30901
        hostPort: 30901
        protocol: TCP
      - containerPort: 30265
        hostPort: 30265
        protocol: TCP
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 31001
        hostPort: 31001
        protocol: TCP
  - role: worker
  - role: worker
