apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-job-runner
  namespace: kaiyuan-ray
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ray-job-runner-role
  namespace: kaiyuan-ray
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - events
      - secrets
      - persistentvolumeclaims
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ray-job-runner-rolebinding
  namespace: kaiyuan-ray
subjects:
  - kind: ServiceAccount
    name: ray-job-runner
    namespace: kaiyuan-ray
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ray-job-runner-role
